version: "3.9"
services:
  db:
    build: ./database/
    container_name: postgres_database
    env_file:
      - ./app/database.env
    ports:
      - '5432:5432'
    restart: always
    hostname: localhost
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "username", "-d", "database"]
      interval: 3s
      timeout: 3s
      retries: 5
  app :
    build: ./app
    container_name: python_app
    depends_on:
      db:
        condition: service_healthy